apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.docker.internal:6443
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: exercises/helm-nginx
    repoURL: https://github.com/onlife2007/nd064_course_1
    targetRevision: HEAD
